/*
 * GriffNode API
 *
 * Accept Bitcoin, Litecoin, Dogecoin, Dash, Ethereum and ERC-20 tokens. Server-to-server, authenticated with a secret API key (`Authorization: Bearer sk_live_…` for live, or `sk_test_…` for test mode — same base URL). All monetary amounts in API responses are JSON numbers; **webhook** amounts are strings to preserve decimal precision (see the `webhooks` section).  **Rate limits.** Every request is rate-limited per API key in two windows — per minute and per hour — by plan tier (min/hour): starter 30/500, business 100/2000, professional 300/5000, enterprise 1000/20000. Every response carries `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` (Unix seconds) for the per-minute window. On `429` the body is `error: \"RATE_LIMIT_EXCEEDED\"` (either window) with a `Retry-After` header (seconds) — clients should retry after it. A separate `429` with `error: \"MONTHLY_LIMIT_REACHED\"` means the plan's monthly transaction quota (not the request rate). 
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateDetailedTransactionRequest {
    #[serde(rename = "crypto")]
    pub crypto: models::CryptoSymbol,
    #[serde(rename = "currency_fiat", skip_serializing_if = "Option::is_none")]
    pub currency_fiat: Option<models::FiatCurrency>,
    #[serde(rename = "items")]
    pub items: Vec<models::LineItem>,
    #[serde(rename = "order_id")]
    pub order_id: String,
    /// Free-form key/value (≤20 keys, string values ≤500 chars, ≤4 KB total).
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<std::collections::HashMap<String, String>>,
    #[serde(rename = "customer_email", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub customer_email: Option<Option<String>>,
    #[serde(rename = "success_url", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub success_url: Option<Option<String>>,
    #[serde(rename = "cancel_url", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub cancel_url: Option<Option<String>>,
}

impl CreateDetailedTransactionRequest {
    pub fn new(crypto: models::CryptoSymbol, items: Vec<models::LineItem>, order_id: String) -> CreateDetailedTransactionRequest {
        CreateDetailedTransactionRequest {
            crypto,
            currency_fiat: None,
            items,
            order_id,
            metadata: None,
            customer_email: None,
            success_url: None,
            cancel_url: None,
        }
    }
}

