/*
 * GriffNode API
 *
 * Accept Bitcoin, Litecoin, Dogecoin, Dash, Ethereum and ERC-20 tokens. Server-to-server, authenticated with a secret API key (`Authorization: Bearer sk_live_…` for live, or `sk_test_…` for test mode — same base URL). All monetary amounts in API responses are JSON numbers; **webhook** amounts are strings to preserve decimal precision (see the `webhooks` section).  **Rate limits.** Every request is rate-limited per API key in two windows — per minute and per hour — by plan tier (min/hour): starter 30/500, business 100/2000, professional 300/5000, enterprise 1000/20000. Every response carries `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` (Unix seconds) for the per-minute window. On `429` the body is `error: \"RATE_LIMIT_EXCEEDED\"` (either window) with a `Retry-After` header (seconds) — clients should retry after it. A separate `429` with `error: \"MONTHLY_LIMIT_REACHED\"` means the plan's monthly transaction quota (not the request rate). 
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CryptoSymbol : Supported coin/token symbol. /cryptos/list is authoritative at runtime.
/// Supported coin/token symbol. /cryptos/list is authoritative at runtime.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CryptoSymbol {
    #[serde(rename = "BTC")]
    Btc,
    #[serde(rename = "LTC")]
    Ltc,
    #[serde(rename = "DOGE")]
    Doge,
    #[serde(rename = "DASH")]
    Dash,
    #[serde(rename = "ETH")]
    Eth,
    #[serde(rename = "USDT")]
    Usdt,
    #[serde(rename = "USDC")]
    Usdc,
    #[serde(rename = "DAI")]
    Dai,
    #[serde(rename = "WBTC")]
    Wbtc,
    #[serde(rename = "SHIB")]
    Shib,
    #[serde(rename = "PEPE")]
    Pepe,
    #[serde(rename = "LINK")]
    Link,
    #[serde(rename = "UNI")]
    Uni,
    #[serde(rename = "AAVE")]
    Aave,
    #[serde(rename = "MKR")]
    Mkr,

}

impl std::fmt::Display for CryptoSymbol {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Btc => write!(f, "BTC"),
            Self::Ltc => write!(f, "LTC"),
            Self::Doge => write!(f, "DOGE"),
            Self::Dash => write!(f, "DASH"),
            Self::Eth => write!(f, "ETH"),
            Self::Usdt => write!(f, "USDT"),
            Self::Usdc => write!(f, "USDC"),
            Self::Dai => write!(f, "DAI"),
            Self::Wbtc => write!(f, "WBTC"),
            Self::Shib => write!(f, "SHIB"),
            Self::Pepe => write!(f, "PEPE"),
            Self::Link => write!(f, "LINK"),
            Self::Uni => write!(f, "UNI"),
            Self::Aave => write!(f, "AAVE"),
            Self::Mkr => write!(f, "MKR"),
        }
    }
}

impl Default for CryptoSymbol {
    fn default() -> CryptoSymbol {
        Self::Btc
    }
}

