/*
 * GriffNode API
 *
 * Accept Bitcoin, Litecoin, Dogecoin, Dash, Ethereum and ERC-20 tokens. Server-to-server, authenticated with a secret API key (`Authorization: Bearer sk_live_…` for live, or `sk_test_…` for test mode — same base URL). All monetary amounts in API responses are JSON numbers; **webhook** amounts are strings to preserve decimal precision (see the `webhooks` section).  **Rate limits.** Every request is rate-limited per API key in two windows — per minute and per hour — by plan tier (min/hour): starter 30/500, business 100/2000, professional 300/5000, enterprise 1000/20000. Every response carries `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` (Unix seconds) for the per-minute window. On `429` the body is `error: \"RATE_LIMIT_EXCEEDED\"` (either window) with a `Retry-After` header (seconds) — clients should retry after it. A separate `429` with `error: \"MONTHLY_LIMIT_REACHED\"` means the plan's monthly transaction quota (not the request rate). 
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetStats200ResponseData {
    #[serde(rename = "total_transactions", skip_serializing_if = "Option::is_none")]
    pub total_transactions: Option<i32>,
    #[serde(rename = "monthly_transactions", skip_serializing_if = "Option::is_none")]
    pub monthly_transactions: Option<i32>,
    #[serde(rename = "total_volume_fiat", skip_serializing_if = "Option::is_none")]
    pub total_volume_fiat: Option<f64>,
    #[serde(rename = "unique_customers", skip_serializing_if = "Option::is_none")]
    pub unique_customers: Option<i32>,
}

impl GetStats200ResponseData {
    pub fn new() -> GetStats200ResponseData {
        GetStats200ResponseData {
            total_transactions: None,
            monthly_transactions: None,
            total_volume_fiat: None,
            unique_customers: None,
        }
    }
}

