/*
 * GriffNode API
 *
 * Accept Bitcoin, Litecoin, Dogecoin, Dash, Ethereum and ERC-20 tokens. Server-to-server, authenticated with a secret API key (`Authorization: Bearer sk_live_…` for live, or `sk_test_…` for test mode — same base URL). All monetary amounts in API responses are JSON numbers; **webhook** amounts are strings to preserve decimal precision (see the `webhooks` section).  **Rate limits.** Every request is rate-limited per API key in two windows — per minute and per hour — by plan tier (min/hour): starter 30/500, business 100/2000, professional 300/5000, enterprise 1000/20000. Every response carries `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` (Unix seconds) for the per-minute window. On `429` the body is `error: \"RATE_LIMIT_EXCEEDED\"` (either window) with a `Retry-After` header (seconds) — clients should retry after it. A separate `429` with `error: \"MONTHLY_LIMIT_REACHED\"` means the plan's monthly transaction quota (not the request rate). 
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Plan {
    #[serde(rename = "tier", skip_serializing_if = "Option::is_none")]
    pub tier: Option<models::PlanTier>,
    #[serde(rename = "monthly_price_usd", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub monthly_price_usd: Option<Option<f64>>,
    #[serde(rename = "yearly_price_usd", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub yearly_price_usd: Option<Option<f64>>,
    #[serde(rename = "monthly_transaction_limit", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub monthly_transaction_limit: Option<Option<i32>>,
    #[serde(rename = "overage_cost_per_tx", skip_serializing_if = "Option::is_none")]
    pub overage_cost_per_tx: Option<f64>,
    #[serde(rename = "webhook_support", skip_serializing_if = "Option::is_none")]
    pub webhook_support: Option<bool>,
    #[serde(rename = "webhook_limit", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub webhook_limit: Option<Option<i32>>,
    #[serde(rename = "ip_whitelist", skip_serializing_if = "Option::is_none")]
    pub ip_whitelist: Option<bool>,
    #[serde(rename = "api_rate_limit_per_minute", skip_serializing_if = "Option::is_none")]
    pub api_rate_limit_per_minute: Option<i32>,
    #[serde(rename = "api_rate_limit_per_hour", skip_serializing_if = "Option::is_none")]
    pub api_rate_limit_per_hour: Option<i32>,
    #[serde(rename = "custom_pricing", skip_serializing_if = "Option::is_none")]
    pub custom_pricing: Option<bool>,
}

impl Plan {
    pub fn new() -> Plan {
        Plan {
            tier: None,
            monthly_price_usd: None,
            yearly_price_usd: None,
            monthly_transaction_limit: None,
            overage_cost_per_tx: None,
            webhook_support: None,
            webhook_limit: None,
            ip_whitelist: None,
            api_rate_limit_per_minute: None,
            api_rate_limit_per_hour: None,
            custom_pricing: None,
        }
    }
}

