/*
 * GriffNode API
 *
 * Accept Bitcoin, Litecoin, Dogecoin, Dash, Ethereum and ERC-20 tokens. Server-to-server, authenticated with a secret API key (`Authorization: Bearer sk_live_…` for live, or `sk_test_…` for test mode — same base URL). All monetary amounts in API responses are JSON numbers; **webhook** amounts are strings to preserve decimal precision (see the `webhooks` section).  **Rate limits.** Every request is rate-limited per API key in two windows — per minute and per hour — by plan tier (min/hour): starter 30/500, business 100/2000, professional 300/5000, enterprise 1000/20000. Every response carries `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` (Unix seconds) for the per-minute window. On `429` the body is `error: \"RATE_LIMIT_EXCEEDED\"` (either window) with a `Retry-After` header (seconds) — clients should retry after it. A separate `429` with `error: \"MONTHLY_LIMIT_REACHED\"` means the plan's monthly transaction quota (not the request rate). 
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Transaction : The canonical, curated public view of a transaction (same shape from create, get and list). Internal fields (capability tokens, client_ip, address_index, derivation/db internals) are deliberately NOT exposed. 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Transaction {
    #[serde(rename = "transaction_id")]
    pub transaction_id: String,
    #[serde(rename = "status")]
    pub status: models::TransactionStatus,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<Type>,
    #[serde(rename = "crypto")]
    pub crypto: models::CryptoSymbol,
    #[serde(rename = "deposit_address", skip_serializing_if = "Option::is_none")]
    pub deposit_address: Option<String>,
    #[serde(rename = "amount_crypto", skip_serializing_if = "Option::is_none")]
    pub amount_crypto: Option<f64>,
    #[serde(rename = "amount_fiat")]
    pub amount_fiat: f64,
    #[serde(rename = "amount_usd")]
    pub amount_usd: f64,
    #[serde(rename = "amount_paid", skip_serializing_if = "Option::is_none")]
    pub amount_paid: Option<f64>,
    #[serde(rename = "amount_remaining", skip_serializing_if = "Option::is_none")]
    pub amount_remaining: Option<f64>,
    #[serde(rename = "currency_fiat")]
    pub currency_fiat: models::FiatCurrency,
    #[serde(rename = "fiat_to_usd_rate", skip_serializing_if = "Option::is_none")]
    pub fiat_to_usd_rate: Option<f64>,
    /// USD per unit of crypto, locked at creation.
    #[serde(rename = "exchange_rate", skip_serializing_if = "Option::is_none")]
    pub exchange_rate: Option<f64>,
    #[serde(rename = "confirmations_required", skip_serializing_if = "Option::is_none")]
    pub confirmations_required: Option<i32>,
    #[serde(rename = "payment_url", skip_serializing_if = "Option::is_none")]
    pub payment_url: Option<String>,
    #[serde(rename = "order_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub order_id: Option<Option<String>>,
    #[serde(rename = "customer_email", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub customer_email: Option<Option<String>>,
    #[serde(rename = "items", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub items: Option<Option<Vec<models::LineItem>>>,
    /// On-chain payments detected toward this transaction.
    #[serde(rename = "payments", skip_serializing_if = "Option::is_none")]
    pub payments: Option<Vec<models::PaymentSplit>>,
    /// Free-form key/value (≤20 keys, string values ≤500 chars, ≤4 KB total).
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<std::collections::HashMap<String, String>>,
    #[serde(rename = "success_url", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub success_url: Option<Option<String>>,
    #[serde(rename = "cancel_url", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub cancel_url: Option<Option<String>>,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
    #[serde(rename = "expires_at")]
    pub expires_at: String,
}

impl Transaction {
    /// The canonical, curated public view of a transaction (same shape from create, get and list). Internal fields (capability tokens, client_ip, address_index, derivation/db internals) are deliberately NOT exposed. 
    pub fn new(transaction_id: String, status: models::TransactionStatus, crypto: models::CryptoSymbol, amount_fiat: f64, amount_usd: f64, currency_fiat: models::FiatCurrency, created_at: String, expires_at: String) -> Transaction {
        Transaction {
            transaction_id,
            status,
            r#type: None,
            crypto,
            deposit_address: None,
            amount_crypto: None,
            amount_fiat,
            amount_usd,
            amount_paid: None,
            amount_remaining: None,
            currency_fiat,
            fiat_to_usd_rate: None,
            exchange_rate: None,
            confirmations_required: None,
            payment_url: None,
            order_id: None,
            customer_email: None,
            items: None,
            payments: None,
            metadata: None,
            success_url: None,
            cancel_url: None,
            created_at,
            updated_at: None,
            expires_at,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "basic")]
    Basic,
    #[serde(rename = "detailed")]
    Detailed,
}

impl Default for Type {
    fn default() -> Type {
        Self::Basic
    }
}

