/*
 * GriffNode API
 *
 * Accept Bitcoin, Litecoin, Dogecoin, Dash, Ethereum and ERC-20 tokens. Server-to-server, authenticated with a secret API key (`Authorization: Bearer sk_live_…` for live, or `sk_test_…` for test mode — same base URL). All monetary amounts in API responses are JSON numbers; **webhook** amounts are strings to preserve decimal precision (see the `webhooks` section).  **Rate limits.** Every request is rate-limited per API key in two windows — per minute and per hour — by plan tier (min/hour): starter 30/500, business 100/2000, professional 300/5000, enterprise 1000/20000. Every response carries `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` (Unix seconds) for the per-minute window. On `429` the body is `error: \"RATE_LIMIT_EXCEEDED\"` (either window) with a `Retry-After` header (seconds) — clients should retry after it. A separate `429` with `error: \"MONTHLY_LIMIT_REACHED\"` means the plan's monthly transaction quota (not the request rate). 
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WebhookPayload : Payment-event payload. AMOUNTS ARE STRINGS (e.g. \"100.00\", \"0.00109462\") to preserve decimal precision — parse before arithmetic. 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebhookPayload {
    #[serde(rename = "event")]
    pub event: Event,
    #[serde(rename = "timestamp")]
    pub timestamp: String,
    #[serde(rename = "transaction_id")]
    pub transaction_id: String,
    #[serde(rename = "status")]
    pub status: models::TransactionStatus,
    #[serde(rename = "currency_crypto", skip_serializing_if = "Option::is_none")]
    pub currency_crypto: Option<models::CryptoSymbol>,
    #[serde(rename = "currency_fiat", skip_serializing_if = "Option::is_none")]
    pub currency_fiat: Option<models::FiatCurrency>,
    /// Decimal string.
    #[serde(rename = "amount_fiat", skip_serializing_if = "Option::is_none")]
    pub amount_fiat: Option<String>,
    /// Decimal string.
    #[serde(rename = "amount_usd", skip_serializing_if = "Option::is_none")]
    pub amount_usd: Option<String>,
    /// Decimal string.
    #[serde(rename = "amount_crypto", skip_serializing_if = "Option::is_none")]
    pub amount_crypto: Option<String>,
    #[serde(rename = "order_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub order_id: Option<Option<String>>,
    /// Present on completed/overpaid.
    #[serde(rename = "receipt_url", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub receipt_url: Option<Option<String>>,
    /// Free-form key/value (≤20 keys, string values ≤500 chars, ≤4 KB total).
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<std::collections::HashMap<String, String>>,
}

impl WebhookPayload {
    /// Payment-event payload. AMOUNTS ARE STRINGS (e.g. \"100.00\", \"0.00109462\") to preserve decimal precision — parse before arithmetic. 
    pub fn new(event: Event, timestamp: String, transaction_id: String, status: models::TransactionStatus) -> WebhookPayload {
        WebhookPayload {
            event,
            timestamp,
            transaction_id,
            status,
            currency_crypto: None,
            currency_fiat: None,
            amount_fiat: None,
            amount_usd: None,
            amount_crypto: None,
            order_id: None,
            receipt_url: None,
            metadata: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Event {
    #[serde(rename = "payment.created")]
    Created,
    #[serde(rename = "payment.pending")]
    Pending,
    #[serde(rename = "payment.completed")]
    Completed,
    #[serde(rename = "payment.overpaid")]
    Overpaid,
    #[serde(rename = "payment.partial")]
    Partial,
    #[serde(rename = "payment.expired")]
    Expired,
    #[serde(rename = "payment.failed")]
    Failed,
}

impl Default for Event {
    fn default() -> Event {
        Self::Created
    }
}

